server:
  port: 8080
spring:
  datasource:
    hikari:
      mybatisdemo:
        jdbc-url: jdbc:mysql://42.192.77.73:3307/db0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 4245257
        driver-class-name: com.mysql.cj.jdbc.Driver
#jackxu:
#  format:
#    type: gson