server:
  port: 8080
spring:
  datasource:
    hikari:
      mybatisdemo:
        jdbc-url: jdbc:mysql://localhost:3306/mybatisdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
#jackxu:
#  format:
#    type: gson